---
title: "Simulation: No time-dependent covariates"
output: html_document
date: "2024-10-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  out.width = "100%"
)
set.seed(1)

library(ggplot2)
```

## Generate the data

```{r sim1 data generation}
library(survival)
library(simsurv)

# Simulate data
n <- 10000
x <- data.frame(trt = rbinom(n, 1, 0.5), x1 = rnorm(n), x2 = runif(n, -1, 1))
simdat <- simsurv(dist = "weibull", lambdas = 0.1, gammas = 2.5, betas = c(trt = -2, x2 = 1),
                  x = x, maxt = 10)
y <- simdat[, -1]
colnames(y)[1] <- "time"
dat <- cbind(y, x)

# Train/test
idx <- sample(n, 9500)
train <- dat[idx, ]
test <- dat[-idx, ]

# Show time-dependent covariates
dat_temp <- dat
dat_temp$x2 <- as.factor(round(dat_temp$x2 * 5))
dat_temp$trt <- as.factor(dat_temp$trt)
ggplot(dat_temp, aes(x = time)) + 
  geom_density(aes(colour = x2, fill = x2), alpha = 0.1) +
  theme_minimal() +
  facet_grid(cols = vars(trt), labeller = label_both) +
  scale_fill_viridis_d() +
  scale_colour_viridis_d() +
  labs(x = "Time", y = "Density", fill = "Value of X2", colour = "Value of X2",
       title = "Occurrence of the event over time by treatment group and X2")

```

## Fit the models
```{r utils1, echo = FALSE}
fit_model <- function(model, train, test) {
  callr::r(function(model, train, test) {
    library(survivalmodels)
    library(survival)
    reticulate::use_condaenv("Survinng", required = TRUE)
    set.seed(1)
    set_seed(1)
    
    # Fit model
    if (model == "CoxTime") {
      model <- coxtime(Surv(time, status) ~ ., data = train, verbose = FALSE, epochs = 500L,
                     early_stopping = TRUE, frac = 0.33, batch_size = 1024L, patience = 10L,
                     dropout = 0.1)
    } else if (model == "DeepHit") {
      model <- deephit(Surv(time, status) ~ ., data = train, verbose = FALSE, epochs = 500L,
                     early_stopping = TRUE, frac = 0.33, patience = 10L, cuts = 30, 
                     batch_size = 1024L, dropout = 0.1)
    } else if (model == "DeepSurv") {
      model <- deepsurv(Surv(time, status) ~ ., data = train, verbose = FALSE, epochs = 100L,
                      early_stopping = TRUE, frac = 0.33, patience = 10L, batch_size = 1024L,
                      dropout = 0.1)
    } else {
      stop("Model not found")
    }
    
    # Make predictions
    pred <- predict(model, newdata = test, type = "survival")
    dat <- data.frame(
      pred = c(pred), 
      time = rep(as.numeric(colnames(pred)), each = nrow(pred)),
      id = rep(1:nrow(pred), ncol(pred))
    )
    list(Survinng::extract_model(model), pred = dat)
  }, list(model, train, test))
}

plot_survival <- function(dat, test, id_lim = 10, label = "") {
  test <- test[seq_len(id_lim), -1]
  test$id <- seq_len(nrow(test))
  dat <- dat[dat$id <= id_lim, ]
  dat <- merge(test, dat, by = "id")
  ggplot(dat, aes(x = time, y = pred, group = id)) +
    geom_line(aes(colour = factor(id)), alpha = 0.5) +
    geom_point(aes(colour = factor(id)), alpha = 0.5, size = 0.1) +
    theme_minimal() +
    facet_grid(cols = vars(trt)) +
    labs(x = "Time", y = paste0("Survival ", label), colour = "ID")
}
```

```{r sim1 fit models, fig.width=10, fig.height=15}
# Fit the models
ext_deephit <- fit_model("DeepHit", train, test)
ext_coxtime <- fit_model("CoxTime", train, test)
ext_deepsurv <- fit_model("DeepSurv", train, test)

# Show results
p1 <- plot_survival(ext_deephit$pred, test, label = "(DeepHit)")
p2 <- plot_survival(ext_coxtime$pred, test, label = "(CoxTime)")
p3 <- plot_survival(ext_deepsurv$pred, test, label = "(DeepSurv)")
cowplot::plot_grid(p1, p2, p3, nrow = 3)
```


## Create Explainer

```{r sim1 explainer}
library(Survinng)
library(torch)

# Extract predictions
pred_deephit <- ext_deephit$pred
pred_coxtime <- ext_coxtime$pred
pred_deepsurv <- ext_deepsurv$pred

# Create explainer
exp_deephit <- explain(ext_deephit[[1]], data = test)
exp_coxtime <- explain(ext_coxtime[[1]], data = test)
exp_deepsurv <- explain(ext_deepsurv[[1]], data = test)

# Validate predictions
# x <- lapply(exp_deephit$input_data, function(x) torch_tensor(as.matrix(x)))
# pred <- as.array(exp_deephit$model$forward(exp_deephit$model$preprocess_fun(x), target = "survival")[[1]]$squeeze())
# pred_deephit$pred_ref <- c(pred)
# x <- lapply(exp_coxtime$input_data, function(x) torch_tensor(as.matrix(x)))
# pred <- as.array(exp_coxtime$model$forward(exp_coxtime$model$preprocess_fun(x), target = "survival")[[1]]$squeeze())
# pred_coxtime$pred_ref <- c(pred)
# x <- lapply(exp_deepsurv$input_data, function(x) torch_tensor(as.matrix(x)))
# pred <- as.array(exp_deepsurv$model$forward(exp_deepsurv$model$preprocess_fun(x), target = "survival")[[1]]$squeeze())
# pred_deepsurv$pred_ref <- c(pred)
# 
# # Show results
# res <- rbind(
#   cbind(pred_deephit, model = "DeepHit"),
#   cbind(pred_coxtime, model = "CoxTime"),
#   cbind(pred_deepsurv, model = "DeepSurv")
# )
# 
# ggplot(res, aes(x = model, y = pred - pred_ref)) +
#   geom_boxplot() +
#   geom_hline(yintercept = 0, linetype = "dashed") +
#   theme_minimal() +
#   labs(x = "Method", y = "Difference in survival", title = "Difference in survival between predictions and reference")

```


## Survival Attribution
```{r sim1 patients}
head(test)
```

### Gradient (Sensitivity)

```{r sim1 gradient, fig.width=10, fig.height=15}
grad_cox <- surv_grad(exp_coxtime, target = "survival", instance = c(1,2))
grad_deephit <- surv_grad(exp_deephit, target = "survival", instance = c(1,2))
grad_deepsurv <- surv_grad(exp_deepsurv, target = "survival", instance = c(1,2))

cowplot::plot_grid(plot(grad_cox), plot(grad_deephit), plot(grad_deepsurv),
                   nrow = 3, labels = c("CoxTime", "DeepHit", "DeepSurv"))

cowplot::plot_grid(plot(grad_cox, normalize = TRUE), 
                   plot(grad_deephit, normalize = TRUE), 
                   plot(grad_deepsurv, normalize = TRUE),
                   nrow = 3, labels = c("CoxTime", "DeepHit", "DeepSurv"))
```

### SmoothGrad (Sensitivity)

```{r sim1 smoothgrad, fig.width=10, fig.height=15}
sg_cox <- surv_smoothgrad(exp_coxtime, target = "survival", instance = c(1,2), n = 50, noise_level = 0.4)
sg_deephit <- surv_smoothgrad(exp_deephit, target = "survival", instance = c(1,2), n = 50, noise_level = 0.4)
sg_deepsurv <- surv_smoothgrad(exp_deepsurv, target = "survival", instance = c(1,2), n = 50, noise_level = 0.4)

cowplot::plot_grid(plot(sg_cox), plot(sg_deephit), plot(sg_deepsurv),
                   nrow = 3, labels = c("CoxTime", "DeepHit", "DeepSurv"))
```

### Integrated Gradients

```{r sim1 intgrad, fig.width=14, fig.height=8}
x_ref <- list(as.matrix(test[2, -c(1,2)]))
intgrad_cox <- surv_intgrad(exp_coxtime, target = "survival", x_ref = x_ref, n = 100)
intgrad_deephit <- surv_intgrad(exp_deephit, target = "survival", x_ref = x_ref, n = 100)
intgrad_deepsurv <- surv_intgrad(exp_deepsurv, target = "survival", x_ref = x_ref, n = 100)

cowplot::plot_grid(plot(intgrad_cox, add_sum = TRUE), 
                   plot(intgrad_deephit, add_sum = TRUE), 
                   plot(intgrad_deepsurv, add_sum = TRUE),
                   ncol = 3, labels = c("CoxTime", "DeepHit", "DeepSurv"))
cowplot::plot_grid(plot(intgrad_cox, normalize = TRUE), 
                   plot(intgrad_deephit, normalize = TRUE), 
                   plot(intgrad_deepsurv, normalize = TRUE),
                   ncol = 3, labels = c("CoxTime", "DeepHit", "DeepSurv"))
```

### GradientSHAP

```{r sim1 gradSHAP, fig.width=14, fig.height=8}
shap_cox <- surv_gradSHAP(exp_coxtime, target = "survival", n = 20, num_samples = 500)
shap_deephit <- surv_gradSHAP(exp_deephit, target = "survival", n = 20, num_samples = 500)
shap_deepsurv <- surv_gradSHAP(exp_deepsurv, target = "survival", n = 20, num_samples =500)

cowplot::plot_grid(plot(shap_cox, add_sum = TRUE), plot(shap_deephit, add_sum = TRUE), 
                   plot(shap_deepsurv, add_sum = TRUE),
                   ncol = 3, labels = c("CoxTime", "DeepHit", "DeepSurv"))

cowplot::plot_grid(plot(shap_cox, normalize = TRUE), 
                   plot(shap_deephit, normalize = TRUE), 
                   plot(shap_deepsurv, normalize = TRUE),
                   ncol = 3, labels = c("CoxTime", "DeepHit", "DeepSurv")) 

```


