
test_that("Method 'surv_smoothgrad' with CoxTime (1D model)", {
  # Preparation ----------------------------------------------------------------
  model_1d <- seq_model_1D(6)
  data <- torch_randn(10, 5)
  base_hazard <- get_base_hazard(20)
  exp_1d <- explain(model_1d, data = data, model_type = "coxtime",
                    baseline_hazard = base_hazard)

  # Test arguments -------------------------------------------------------------
  expect_error(surv_smoothgrad("no explainer"))
  res <- surv_smoothgrad(exp_1d)
  expect_error(surv_smoothgrad(exp_1d, n = "not a number"))
  expect_error(surv_smoothgrad(exp_1d, noise_level = "not a number"))
  expect_error(surv_smoothgrad(exp_1d, target = "wrong target"))
  expect_error(surv_smoothgrad(exp_1d, instance = "wrong instance"))
  expect_error(surv_smoothgrad(exp_1d, times_input = list("not boolean")))
  expect_error(surv_smoothgrad(exp_1d, use_base_hazard = list("not boolean")))
  expect_error(surv_smoothgrad(exp_1d, batch_size = "not integer"))
  expect_error(surv_smoothgrad(exp_1d, include_time = "not boolean"))
  expect_error(surv_smoothgrad(exp_1d, dtype = "wrong dtype"))

  # Test sequential 1D model ---------------------------------------------------
  res <- surv_smoothgrad(exp_1d, instance = c(1, 3))
  expect_s3_class(res, "surv_result")
  checkmate::expect_names(names(res), subset.of = c("res", "pred", "time", "method", "method_args", "competing_risks", "model_class"))
  expect_equal(res$method, "Surv_SmoothGrad")
  expect_equal(res$model_class, "CoxTime")
  expect_equal(res$competing_risks, FALSE)
  expect_equal(res$method_args$target, "survival")
  expect_equal(res$method_args$dtype, "float")
  expect_equal(res$method_args$times_input, FALSE)
  expect_equal(dim(res$res), c(2, 5, 20))
  expect_equal(dim(res$pred), c(2, 20))
  expect_equal(length(res$time), 20)
  checkmate::expect_array(res$res)
  checkmate::expect_array(res$pred)
  expect_vector(res$time)

  # Test sequential 1D model with times_input = TRUE ---------------------------
  res <- surv_smoothgrad(exp_1d, instance = c(1, 3), times_input = TRUE)
  expect_equal(res$method_args$times_input, TRUE)
  expect_equal(res$competing_risks, FALSE)
  expect_equal(res$method_args$target, "survival")
  expect_equal(res$method_args$dtype, "float")
  expect_equal(dim(res$res), c(2, 5, 20))
  expect_equal(dim(res$pred), c(2, 20))
  expect_equal(length(res$time), 20)
  checkmate::expect_array(res$res)
  checkmate::expect_array(res$pred)
  expect_vector(res$time)

  # Test sequential 1D model with other targets --------------------------------
  res <- surv_smoothgrad(exp_1d, instance = c(1, 3), target = "hazard")
  expect_equal(res$method_args$target, "hazard")
  expect_equal(res$method_args$dtype, "float")
  expect_equal(dim(res$res), c(2, 5, 20))
  expect_equal(dim(res$pred), c(2, 20))
  expect_equal(length(res$time), 20)
  res <- surv_smoothgrad(exp_1d, instance = c(1, 3), target = "cum_hazard")
  expect_equal(res$method_args$target, "cum_hazard")
  expect_equal(res$method_args$dtype, "float")
  expect_equal(dim(res$res), c(2, 5, 20))
  expect_equal(dim(res$pred), c(2, 20))
  expect_equal(length(res$time), 20)
  res <- surv_smoothgrad(exp_1d, instance = c(1, 3), target = "survival")
  expect_equal(res$method_args$target, "survival")
  expect_equal(res$method_args$dtype, "float")
  expect_equal(dim(res$res), c(2, 5, 20))
  expect_equal(dim(res$pred), c(2, 20))
  expect_equal(length(res$time), 20)

  # Test sequential 1D model with other dtype ----------------------------------
  res <- surv_smoothgrad(exp_1d, instance = c(1, 3), dtype = "double")
  expect_equal(res$method_args$dtype, "double")
  expect_equal(dim(res$res), c(2, 5, 20))
  expect_equal(dim(res$pred), c(2, 20))
  expect_equal(length(res$time), 20)
  res <- surv_smoothgrad(exp_1d, instance = c(1, 3), times_input = TRUE, dtype = "double")
  expect_equal(res$method_args$dtype, "double")
  expect_equal(dim(res$res), c(2, 5, 20))
  expect_equal(dim(res$pred), c(2, 20))
  expect_equal(length(res$time), 20)
})
