---
title: "Example on Real Multi-modal Medical Data"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Survinng)
library(torch)
library(torchvision)
library(ggplot2)
library(data.table)
library(dplyr)
library(here)

# Load helper functions
source(here("vignettes/articles/real_data/utils.R"))

# Set seeds for reproducibility
set.seed(42)
torch_manual_seed(42)
```


## Load model and metadata

```{r}
# Load model metadata
model_metadata <- read.csv(here("vignettes/articles/real_data/metadata.csv"))
n_img_out <- model_metadata$n_img_out
n_out <- model_metadata$n_out
out_bias <- as.logical(model_metadata$out_bias)
n_tab_feat <- model_metadata$Number.of.tabular.features

# Show performance results
model_metadata[, c("Concordance", "Integrated.Brier.score")]

# Load model state dict
model_state_dict <- load_state_dict(here("vignettes/articles/real_data/model.pt"))

# Replicate model
net_image <- torchvision::model_resnet34(num_classes = n_img_out)
model <- MultiModalModel(net_image, tabular_features = rep(1, n_tab_feat),
                         n_out = n_out, n_img_out = n_img_out, out_bias = out_bias)

# Load model state dict
model <- model$load_state_dict(model_state_dict)
model$eval()
model
```

## Load data

```{r}
data <- read.csv(here("vignettes/articles/real_data/deephit_tabular_data.csv"))
test_images <- list.files(here("vignettes/articles/real_data/test"), full.names = FALSE)

# Filter data
data <- data[data$full_path %in% test_images, ]
data_tab <- torch_tensor(as.matrix(data[, c(1, 2, 3, 4)]))
data_img <- torch_stack(lapply(data$full_path, function(x) {
  base_loader(here(paste0("vignettes/articles/real_data/test/", x))) %>%
    (function(x) x[,,1:3]) %>%
    transform_to_tensor() %>%
    transform_center_crop(226) %>%
    transform_normalize(mean = c(0.485, 0.456, 0.406), std = c(0.229, 0.224, 0.225))
}), dim = 1)
```

## Explain model

```{r, cache=TRUE, warning=FALSE}
exp_deephit <- Survinng::explain(model, list(data_img, data_tab), 
                                 model_type = "deephit",
                                 time_bins = seq(0, 17, length.out = n_out))

ids <- 230
orig_img <- base_loader(here(paste0("vignettes/articles/real_data/test/", data[ids, ]$full_path)))

# Run Grad(t)
grad <- surv_grad(exp_deephit, instance = ids, batch_size = 10)
gc()

# Run SG(t)
sgrad <- surv_smoothgrad(exp_deephit, instance = ids, n = 50, 
                         noise_level = 0.3, batch_size = 10)
gc()

# Run IntGrad(t)
intgrad <- surv_intgrad(exp_deephit, instance = ids, n = 50, batch_size = 10) 
gc()

# Run GradSHAP(t)
grad_shap <- surv_gradSHAP(exp_deephit, instance = ids, n = 10, num_samples = 50, 
                           batch_size = 10, replace = FALSE) 
gc()

# Convert to data.tables
grad <- as.data.table(grad)
sgrad <- as.data.table(sgrad)
intgrad <- as.data.table(intgrad)
grad_shap <- as.data.table(grad_shap)
```

```{r, fig.height= 7, fig.width = 12}
plots <- plot_result(grad, orig_img, name = "real_data_grad", as_force = FALSE)
plot_grid(plots[[1]], 
          plot_grid(plots[[3]], plots[[2]], nrow = 1, rel_widths = c(1, 7)),
          rel_heights = c(1, 0.25), nrow = 2)
```

```{r, fig.height= 7, fig.width = 12}
plots <- plot_result(sgrad, orig_img, name = "real_data_sgrad", as_force = FALSE)
plot_grid(plots[[1]], 
          plot_grid(plots[[3]], plots[[2]], nrow = 1, rel_widths = c(1, 7)),
          rel_heights = c(1, 0.25), nrow = 2)
```

```{r, fig.height= 7, fig.width = 12}
plots <- plot_result(intgrad, orig_img, name = "real_data_intgrad", as_force = TRUE)
plot_grid(plots[[1]], 
          plot_grid(plots[[3]], plots[[2]], nrow = 1, rel_widths = c(1, 7)),
          rel_heights = c(1, 0.25), nrow = 2)
```

```{r, fig.height= 7, fig.width = 12}
plots <- plot_result(grad_shap, orig_img, name = "real_data_gradshap", as_force = TRUE)
plot_grid(plots[[1]], 
          plot_grid(plots[[3]], plots[[2]], nrow = 1, rel_widths = c(1, 7)),
          rel_heights = c(1, 0.25), nrow = 2)
```
