---
title: "Interactions in Survival Models"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

```{r setup}
library(Survinng)
library(ggplot2)
set.seed(42)
```

# Time-independent effects

## Generate the data

```{r sim1 data generation}
library(survival)
library(simsurv)

# Simulate data
n <- 10000
x <- data.frame(x1 = rnorm(n), x2 = runif(n, 0, 1), x3 = runif(n, 1, 2))
x$x2x3 <- x$x2 * x$x3
simdat <- simsurv(dist = "weibull", lambdas = 0.1, gammas = 2.5, betas = c(x1 = 1, x2x3 = -2),
                  x = x, maxt = 10)
y <- simdat[, -1]
colnames(y)[1] <- "time"
dat <- cbind(y, x[, -4])

# Train/test
idx <- sample(n, 9500)
train <- dat[idx, ]
test <- dat[-idx, ]
```

## Fit the models
```{r utils1, echo = FALSE}
fit_model <- function(model, train, test) {
  callr::r(function(model, train, test) {
    library(survivalmodels)
    library(survival)
    reticulate::use_condaenv("Survinng", required = TRUE)
    set.seed(1)
    set_seed(1)
    
    # Fit model
    if (model == "CoxTime") {
      model <- coxtime(Surv(time, status) ~ ., data = train, verbose = FALSE, epochs = 500L,
                     early_stopping = TRUE, frac = 0.33, batch_size = 1024L, patience = 10L,
                     dropout = 0.1)
    } else if (model == "DeepHit") {
      model <- deephit(Surv(time, status) ~ ., data = train, verbose = FALSE, epochs = 500L,
                     early_stopping = TRUE, frac = 0.33, patience = 10L, cuts = 30, 
                     batch_size = 1024L, dropout = 0.1)
    } else if (model == "DeepSurv") {
      model <- deepsurv(Surv(time, status) ~ ., data = train, verbose = FALSE, epochs = 100L,
                      early_stopping = TRUE, frac = 0.33, patience = 10L, batch_size = 1024L,
                      dropout = 0.1)
    } else {
      stop("Model not found")
    }
    
    # Make predictions
    pred <- predict(model, newdata = test, type = "survival")
    dat <- data.frame(
      pred = c(pred), 
      time = rep(as.numeric(colnames(pred)), each = nrow(pred)),
      id = rep(1:nrow(pred), ncol(pred))
    )
    list(Survinng::extract_model(model), pred = dat)
  }, list(model, train, test))
}
```

```{r sim1 fit models, fig.width=10, fig.height=15}
# Fit the models
ext_deephit <- fit_model("DeepHit", train, test)
ext_coxtime <- fit_model("CoxTime", train, test)
ext_deepsurv <- fit_model("DeepSurv", train, test)
```


## Create Explainer

```{r sim1 explainer}
library(Survinng)
library(torch)

# Create explainer
exp_deephit <- explain(ext_deephit[[1]], data = test)
exp_coxtime <- explain(ext_coxtime[[1]], data = test)
exp_deepsurv <- explain(ext_deepsurv[[1]], data = test)
```


## Survival Attribution
```{r sim1 patients}
head(test)
```


### Interactions
  
```{r sim1 survival attribution}
inthess_coxtime <- surv_inthess(exp_coxtime, instance = c(1,3), n = 20, batch_size = 1000)
inthess_deephit <- surv_inthess(exp_deephit, instance = c(1,3), n = 20, batch_size = 1000)
inthess_deepsurv <- surv_inthess(exp_deepsurv, instance = c(1,3), n = 20, batch_size = 1000)

cowplot::plot_grid(
  plot(inthess_coxtime, add_sum = TRUE), 
  plot(inthess_deephit, add_sum = TRUE), 
  plot(inthess_deepsurv, add_sum = TRUE),
  nrow = 3, labels = c("CoxTime", "DeepHit", "DeepSurv"))
```
